language: python
python:
  - "pypy"
  - "pypy3"
  - "2.7"
  - "3.2"
  - "3.3"
  - "3.4"
# http://docs.travis-ci.com/user/languages/python/
install:
  - for PPA in $PPAS; do sudo add-apt-repository --yes $PPA; done
  - sudo apt-get update -qq
# need libllvm-x.y      for most tests
# need llvm-x.y-dev     for LTO tests
# need llvm-x.y         for external opt/llc/llvm-as/llvm-dis/llvm-link/llvm-config
# need llvm-x.y-runtime for external lli
# need clang-x.y        for external clang
  - sudo apt-get install libllvm$LLPY_LLVM_VERSION llvm-$LLPY_LLVM_VERSION-dev
script:
  - python ./runtests.py
env:
  - LLPY_LLVM_VERSION=3.0 PPAS=ppa:h-rayflood/llvm
  - LLPY_LLVM_VERSION=3.1 PPAS=ppa:h-rayflood/llvm
  - LLPY_LLVM_VERSION=3.2 PPAS=ppa:h-rayflood/llvm
  - LLPY_LLVM_VERSION=3.3 PPAS=ppa:h-rayflood/llvm
  - LLPY_LLVM_VERSION=3.4 PPAS=ppa:h-rayflood/llvm
  - LLPY_LLVM_VERSION=3.5 PPAS='ppa:h-rayflood/llvm-upper ppa:h-rayflood/gcc-upper'
# https://launchpad.net/~h-rayflood/+archive/ubuntu/llvm
# https://launchpad.net/~h-rayflood/+archive/ubuntu/llvm-upper
