language: python
python:
  - "3.2"
  - "3.3"
install:
  - sudo apt-get update -qq
  - sudo apt-get install libllvm$LLPY_LLVM_VERSION
script:
  - ./runtests.py
env:
  - LLPY_LLVM_VERSION=3.0
  - LLPY_LLVM_VERSION=3.1
  - LLPY_LLVM_VERSION=3.2
#  - LLPY_LLVM_VERSION=3.3    Not available in precise
